config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    # get "users", to: "devise/sessions#new"
    get "users", to: "devise/sessions#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end  
  root "home#index"
  get "integration", to: "integration#index"
  get "callback_integration", to: "integration#facebook_callback"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "disconnect_facebook", to: "integration#destroy_session"
  get "share_post", to: "integration#post_content"
  post "microphone", to: "templates#show_microphone"
  get "record_audio", to: "templates#record_microphone_audionew"
  get "text_to_speech", to: "templates#text_to_speech"
  get "templates/audio_index"
  get "videos/render_video"
  get "generate_text", to: "chat_gpt#new"
  get "send_response", to: "chat_gpt#send_to_chat"
  post "search_image", to: "templates#image_search"
  post "search_video", to: "templates#video_search"
  get "text_to_video", to: "reels#text_to_video"
  get "send_url", to: "reels#fetch_url"
  post '/shotstack_callback', to: 'reels#text_to_video'
  get "stackio_integration/create"
  resources :projects
  resources :reels do
    member do
      get "script", to: "reels#script"
      get "editor", to: "reels#editor"
    end
  end
  resources :templates
  resources :videos, only: [:new, :create, :index]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/views/home/index.html.erb
<div class="bg-secondary">
  <div class="video-background">
    <video autoplay muted loop>
      <%# <source src="https://reeelapps-app.s3.us-west-2.amazonaws.com/content_reel_bg+-video-2+(720p).mp4" type="video/mp4"> %>
      Your browser does not support the video tag.
    </video>
    <div class="content">
      <%= link_to "Create Project",new_project_path, class: 'btn btn-lg text-light border project_create modal_buttons'%>
      <%= link_to 'View Projects',projects_path, class: 'btn btn-lg text-light border project_view modal_buttons'%>
      <%= link_to 'Integrations',  integration_path,class: 'btn btn-lg text-light border integration-button modal_buttons'%>
    </div>
    <div class="container px-5 py-5 px-md-5 text-center text-lg-start my-5">
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
          <h1 class="my-2 display-5 fw-bold ls-tight text-center homepage_heading">
            WELCOME TO <span class="homepage_heading_span">CONTENTREEL</span>
          </h1>
          <p class="mb-4 text-center homepage_demo">
            Instantly create impactful and engaging content videos for your YouTube channel, TikTok,
            Instagram Reels and everything in between.
            Create all shapes and sizes of videos and publish them everyday, dominating niche.
          </p>
          <button class="btn rounded-pill btn-lg btn-block social_connect_button text-light">Watch Demo Videos</button>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Page Content -->