config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    # get "users", to: "devise/sessions#new"
    get "users", to: "devise/sessions#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end  
  root "home#index"
  get "integration", to: "integration#index"
  get "callback_integration", to: "integration#facebook_callback"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "disconnect_facebook", to: "integration#destroy_session"
  get "share_post", to: "integration#post_content"
  post "microphone", to: "templates#show_microphone"
  get "record_audio", to: "templates#record_microphone_audionew"
  get "text_to_speech", to: "templates#text_to_speech"
  get "templates/audio_index"
  get "videos/render_video"
  get "generate_text", to: "chat_gpt#new"
  get "send_response", to: "chat_gpt#send_to_chat"
  post "search_image", to: "templates#image_search"
  post "search_video", to: "templates#video_search"
  get "text_to_video", to: "reels#text_to_video"
  get "send_url", to: "reels#fetch_url"
  post '/shotstack_callback', to: 'reels#text_to_video'
  get "stackio_integration/create"
  resources :projects
  resources :reels do
    member do
      get "script", to: "reels#script"
      get "editor", to: "reels#editor"
    end
  end
  resources :templates
  resources :videos, only: [:new, :create, :index]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :reels,dependent: :destroy
  # Validations :name,presence: true,length: {minimum: 8}
  validates :name, presence: true,length: {minimum: 8}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!,:set_project, only: %i[ show edit update destroy ]
  def index
    @projects = Project.order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project = Project.find_by(id: params[:id])
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control form-control-lg w-100" %>
    <br>
  </div>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="modal-footer col-md-12">
    <%= form.submit class: 'btn btn-dark mt-3', style: 'display:center ' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col-sm-3">

  <div class="card">

    <div class="image-container ">
      <img src="https://content.reelapps.io/static/media/LOGO.c4ba0a75af69c59a6576.png" width="100%" height="100%" class="img-fluid rounded thumbnail-image background-radial-gradient">
    </div>

    <div class="product-details">
      <%=project.name%>
      <br/>
      <%= link_to "Edit",reels_path(project_id:project.id),class: 'btn btn-dark' %>
      <%= link_to "Delete", project, data: { turbo_method: :delete }, class: 'btn btn-danger'%>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%=render 'form' ,project: @project %>

app/views/projects/index.html.erb
<div class="">
  <%= link_to "Create Project",new_project_path, class: 'btn btn-lg text-dark border border-2 project_create modal_buttons'%>
  <div class="container position-relative project-listing">
    <div class="row">
      <%= render partial: "projects/project", collection: @projects %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%=render "form",project: @project%>

app/views/projects/show.html.erb
<%if(@project.reels.count==0) %>
  <%=render partial: 'reels/form',locals: { reel: @project.reels.new} %>

<%else %>
      <div class="wrapper mt-5">

        <div class="container">

          <div class="row g-1">

            <div>

              <div class="col-md-3">

                <div class="card p-3">

                  <div class="text-center">

                    <h1 class="content-reel">Content Reel</h1>

                  </div>

                  <div class="product-details">
                    <%=@project.name%>
                    <br/>
                    <%= link_to "Edit",reels_path(project_id:@project.id),class:'btn btn-dark' %>
                    <%= link_to "Delete", @project, data: { turbo_method: :delete }, class: 'btn btn-danger'%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<%end %>