config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    # get "users", to: "devise/sessions#new"
    get "users", to: "devise/sessions#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end  
  root "home#index"
  get "integration", to: "integration#index"
  get "callback_integration", to: "integration#facebook_callback"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "disconnect_facebook", to: "integration#destroy_session"
  get "share_post", to: "integration#post_content"
  post "microphone", to: "templates#show_microphone"
  get "record_audio", to: "templates#record_microphone_audionew"
  get "text_to_speech", to: "templates#text_to_speech"
  get "templates/audio_index"
  get "videos/render_video"
  get "generate_text", to: "chat_gpt#new"
  get "send_response", to: "chat_gpt#send_to_chat"
  post "search_image", to: "templates#image_search"
  post "search_video", to: "templates#video_search"
  get "text_to_video", to: "reels#text_to_video"
  get "send_url", to: "reels#fetch_url"
  post '/shotstack_callback', to: 'reels#text_to_video'
  get "stackio_integration/create"
  resources :projects
  resources :reels do
    member do
      get "script", to: "reels#script"
      get "editor", to: "reels#editor"
    end
  end
  resources :templates
  resources :videos, only: [:new, :create, :index]
end

app/models/reel.rb
class Reel < ApplicationRecord
  # include ActiveModel::Validations
  belongs_to :project
  has_many :templates
end

app/controllers/reels_controller.rb
class ReelsController < ApplicationController
  before_action :authenticate_user!, :load_data
  before_action :set_reel, only: [:show, :edit, :update, :destroy, :script, :editor]

  def index
    @project = Project.find(params[:project_id])
    @reels = @project.reels.all
  end

  def new
    @project = Project.find(params[:project_id])
    @reel = @project.reels.new
  end

  def create
    @reel = Reel.new(reel_params)
    chat = ChatService.new(content: @reel.video_set)
    @reel.script = chat.chat_data

    if @reel.save
      redirect_to projects_url, notice: "Reel was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @reel.update(reel_params)
    respond_to { |format| format.js { render nothing: true } }
    redirect_back(fallback_location: root_path)
  end

  def destroy
    if @reel.destroy
      redirect_to reels_path(product_id: @reel.project_id), notice: "Project was successfully destroyed."
    end
  end

  def editor
    @templates = @reel.templates.all
  end

  def text_to_video
    fb_token = current_user.facebook_token
    fetch_data = FacebookService.new({token: fb_token})
    @data = fetch_data.facebook_call(fb_token)

    @reel = Reel.find_by(id: params[:reel_id])
    @templates = @reel.templates.last
    script = params[:script_text]
    shots = ShotstackService.new
    audio_src = rails_blob_url(@templates.file, disposition: :inline)
    id = shots.text_to_video(script, audio_src,  session[:video_data_url] , session[:image_data_url])
    api_client = Shotstack::EditApi.new
    sleep(30)
    @result = api_client.get_render(id, { data: false, merged: true }).response
    @reel.url = @result.url
    @reel.save
  end

  def fetch_url
    session[:image_data_url] = params[:image_data_Url]
    session[:video_data_url] = params[:video_data_Url]
  end

  private

  def set_reel
    @reel = Reel.find(params[:id])
  end

  def reel_param
    params.require(:reel).permit(:script)
  end

  def reel_params
    params.require(:reel).permit(:video_set, :keywords, :no_of_video, :platform, :cta, :project_id)
  end

  def load_data
    response = HTTParty.get("https://api.elevenlabs.io/v1/voices")
    @voices = response.parsed_response["voices"]
  end
end

app/helpers/reels_helper.rb
module ReelsHelper
end

app/views/reels/_audio.html.erb
<div>
  <button class="btn btn-lg bg-dark text-light record-audio">Record Audio</button>
</div>
<div class="record-audio-container display-none">
  <%= render partial: "templates/record_microphone_audio"%>
</div>
<div class="col-md-6">
  <div class="card mb-3">
    <%@templates.each do |template| %>
      <% if template.file.attached? && template.file.content_type.include?("audio") %>
        <%=audio_tag(url_for(template.file), controls: true , id: "my-audio") %>
      <% end %>
    <%end %>

  </div>
</div>
<div>
  <button class="btn btn-lg bg-dark text-light text-to-speech">Text To Speech</button>
</div>
<div class="text-to-speech-container display-none">
  <%= render partial: "templates/audio_index"%>
</div>

app/views/reels/_form.html.erb
<%= form_for(reel) do |form| %>
  <% if reel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reel.errors.count, "error") %> prohibited this Reel from being saved:</h2>
      <ul>
        <% reel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-body bg-dark">
    <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3>Create New Reel</h3>
            <p>Fill in the data below.</p>

            <div class="col-md-12">
              <%= form.text_field :video_set, class: " form-control", placeholder: "Video Set" %>
            </div>

            <div class="col-md-12">
              <%= form.text_field :keywords, class: "form-control", placeholder: "Keyword" %>
            </div>

            <div class="col-md-12">
              <%= form.select :platform, [["Facebook", "facebook"], ["Youtube", "youtube"], ["Twitter", "twitter"]], placeholder: "Select the platform", class: "form-select mt-3" %>
            </div>

            <div class="col-md-12">
              <%= form.number_field :no_of_video, class: "form-control mt-3", placeholder: "No Of Video" %>
            </div>

            <div class="form-check">
              <%= form.label :CTA, style: "color:white;text-transform:uppercase", class: "form-check-label" %>
              <%= form.check_box :cta, class: "form-check-input", true_value: true, false_value: false %>
            </div>

            <%= form.hidden_field :project_id, value: reel.project_id %>

            <div class="form-button mt-3">
              <button id="submit" type="submit" class="btn btn-primary">Register</button>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/reels/_reel.html.erb
<div class="col-md-3 ms-5">
  <div class="card p-3">
    <div class="text-center">
      <h1 class="content-reel">Content Reel</h1>
    </div>
    <div class="product-details">
      <%=reel.video_set %>
      <br/>
      <%= link_to "Edit", script_reel_path(id: reel.id), class: "btn btn-dark" %>
      <%= link_to "Delete", reel, data: { turbo_method: :delete }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/reels/_side_bar.html.erb
<header>
  <nav id="sidebarMenu" class="collapse d-lg-block bg-dark sidebar collapse">
    <div class="position-fixed">
      <div class="list-group list-group-flush mt-4">
        <%= link_to "Courses", projects_path, class: "list-group-item list-group-item-action w-100 h-100 px-4 py-4 ripple pse  border rounded-3 fas fa-building fa-fw me-3 mb-2" %>
        <%= link_to "Script", script_reel_path(reel), class: "list-group-item list-group-item-action w-100 h-100 px-4 py-4  border rounded-3 ripple fas fa-bars fa-fw me-3 mb-2" %>
        <%= link_to "Editor", editor_reel_path, class: "list-group-item list-group-item-action w-100 h-100 px-4 py-4  ripple border rounded-3 fas fa-building fa-fw me-3 mb-2" %>
      </div>
    </div>
  </nav>
</header>

app/views/reels/_template.html.erb
<div class="col-md-6">
  <div class="card mb-3">
    <% if template.file.attached? && template.file.content_type.include?("video") %>
      <video controls class="card-img-top" width="60%">
        <source src="<%= url_for(template.file) %>" type="<%= template.file.content_type %>">
      </video>
    <% elsif template.file.attached? && template.file.content_type.include?("audio") %>
      <audio controls class="card-img-top" width="60%">
        <source src="<%= url_for(template.file) %>" type="<%= template.file.content_type %>">
      </audio>
    <% elsif template.file.attached? && template.file.content_type.include?("image") %>
      <%= image_tag url_for(template.file) %>
    <% else %>
      <div class="card-body">
        <p class="card-text">No video file attached and file is not supported.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/reels/edit.html.erb
<h1>Reels#edit</h1>
<p>Find me in app/views/reels/edit.html.erb</p>

app/views/reels/editor.html.erb
<%= render partial: 'reels/side_bar', locals: { reel: @reel } %>
<% selected = "" %>
<div class="editor bg-secondary w-50 h-75">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <ul class="navbar-nav">
            <a class="navbar-brand"><i class="fa fa-text-width d-flex justify-content-center text-light text_size_fa"></i>
              <span class="text-light text_size">Text</span></a>
          </ul>
          <li class="nav-item ms-4">
            <a class="nav-link" aria-current="page"><i class="fa fa-clipboard d-flex justify-content-center text-light text_size"></i>
              <span class="text-light text_size">Background</span></a>
          </li>
          <li class="nav-item ms-4">
            <a class="nav-link" aria-current="page"><i class="fa fa-film d-flex justify-content-center text-light text_size"></i>
              <span class="text-light text_size">Media</span></a>
          </li>
          <li class="nav-item ms-4">
            <a class="nav-link" aria-current="page"><i class="fa fa-headphones d-flex justify-content-center text-light text_size"></i>
              <span class="text-light text_size">Audio</span></a>
          </li>
          <li class="nav-item ms-4">
            <a class="nav-link" aria-current="page"><i class="fa fa-modx d-flex justify-content-center text-light text_size"></i>
              <span class="text-light text_size">Motion</span></a>
          </li>
          <li class="nav-item ms-4">
            <a class="nav-link" aria-current="page"><i class="fa fa-transition d-flex justify-content-center text-light text_size"></i>
              <span class="text-light text_size">Transition</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <img src="https://ichef.bbci.co.uk/images/ic/640x360/p05ccrb2.jpg" width="100%" height="86%">

</div>
<div class="editor1 bg-light w-25 display-block image-list">
  <div class="container ">
    <h1>Image Listing</h1>
    <div class="row">
      <%= render partial: "templates/image_show" %>
    </div>
  </div>
</div>

<div class="editor1 bg-light w-25 display-none video-list ">
  <div class="container ">
    <h1>Video Listing</h1>
    <div class="row">
      <%= render partial: "reels/template", collection: @templates %>
      <%= link_to "Upload Audio", new_template_path(reel_id: @reel.id), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<div class="editor1 bg-light w-25 display-none audio-list">
  <div class="container ">
    <h1>Audio Listing</h1>
    <div class="row">
      <%= render partial: "reels/audio"%>
      <%= link_to "Upload Audio", new_template_path(reel_id: @reel.id), class: 'btn btn-secondary' %>
    </div>
  </div>
</div>


<div class="editor1 bg-light w-25 display-none text-list">
  <div class="container ">
    <h1>Text Listing</h1>
    <div class="row">
      <%= render partial: "templates/text" %>
    </div>
  </div>
</div>

app/views/reels/index.html.erb
<div class="wrapper mt-5 reel-listing">
  <div class="container">
    <div class="row g-1">
      <%= render partial: "reels/reel", collection: @reels %>
      <div class="col-md-3 ms-5">
        <div class="card p-3">
          <%= link_to new_reel_path(project_id: @project.id) do %>
            <i class="fas fa-plus ms-3 "></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

app/views/reels/new.html.erb
<%= render "form", reel: @reel, project: @project %>

app/views/reels/script.html.erb
<%= render partial: "reels/side_bar", locals: { reel: @reel } %>

<% script = @reel.script %>
<%= link_to "Make a video", text_to_video_path(script_text: script, reel_id: params[:id]), class: "btn btn-lg save_buttons1" %>
<%= link_to "Save", script_reel_path, class: "btn btn-lg save_buttons1" %>
<div class="border border-2 rounded-3 script bg-light overflow-scroll">
    <%= best_in_place @reel, :script, :as => :textarea %>
</div>

app/views/reels/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row g-1">
      <div>
        <div class="col-md-3">
          <div class="card p-3">
            <div class="text-center">
              <h1 class="content-reel">Content Reel</h1>
            </div>
            <div class="product-details">
              <%= @reel.video_set %>
              <br/>
              <%= link_to "Edit", edit_project_path(@reel), class: "btn btn-dark" %>
              <%= link_to "Delete", @reel, data: { turbo_method: :delete }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reels/text_to_video.html.erb
<h1>Here is your video</h1>
<%= stylesheet_link_tag 'video' %>

<div class="video-container">
  <video controls>
    <source src="<%= @result.url %>" type="video/mp4">
  </video>
  <%=render partial: "integration/load_fb_data" %>
</div>