config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    # get "users", to: "devise/sessions#new"
    get "users", to: "devise/sessions#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end  
  root "home#index"
  get "integration", to: "integration#index"
  get "callback_integration", to: "integration#facebook_callback"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "disconnect_facebook", to: "integration#destroy_session"
  get "share_post", to: "integration#post_content"
  post "microphone", to: "templates#show_microphone"
  get "record_audio", to: "templates#record_microphone_audionew"
  get "text_to_speech", to: "templates#text_to_speech"
  get "templates/audio_index"
  get "videos/render_video"
  get "generate_text", to: "chat_gpt#new"
  get "send_response", to: "chat_gpt#send_to_chat"
  post "search_image", to: "templates#image_search"
  post "search_video", to: "templates#video_search"
  get "text_to_video", to: "reels#text_to_video"
  get "send_url", to: "reels#fetch_url"
  post '/shotstack_callback', to: 'reels#text_to_video'
  get "stackio_integration/create"
  resources :projects
  resources :reels do
    member do
      get "script", to: "reels#script"
      get "editor", to: "reels#editor"
    end
  end
  resources :templates
  resources :videos, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :reels,dependent: :destroy
  # Validations :name,presence: true,length: {minimum: 8}
  validates :name, presence: true,length: {minimum: 8}
end

app/models/reel.rb
class Reel < ApplicationRecord
  # include ActiveModel::Validations
  belongs_to :project
  has_many :templates
end

app/models/template.rb
class Template < ApplicationRecord
  has_one_attached :file
  belongs_to :reel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :courses
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth, current_user)
    current_user.youtube_token = auth.credentials.token
    current_user.save
  end

  def self.from_fb_omniauth(auth, current_user)
    current_user.facebook_token = auth.credentials.token
    current_user.save
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video_file

  validate :validate_video_format

  def validate_video_format
    if video_file.attached? && !video_file.content_type.in?(%w[video/mp4 video/quicktime])
      errors.add(:video_file, "must be a valid video format")
      video_file.purge
    end
  end
end

app/controllers/chat_gpt_controller.rb
  class ChatGptController < ApplicationController
    def send_to_chat
      image = ChatgptService.new
      image.image_generation
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reels_controller.rb
class ReelsController < ApplicationController
  before_action :authenticate_user!, :load_data
  before_action :set_reel, only: [:show, :edit, :update, :destroy, :script, :editor]

  def index
    @project = Project.find(params[:project_id])
    @reels = @project.reels.all
  end

  def new
    @project = Project.find(params[:project_id])
    @reel = @project.reels.new
  end

  def create
    @reel = Reel.new(reel_params)
    chat = ChatService.new(content: @reel.video_set)
    @reel.script = chat.chat_data

    if @reel.save
      redirect_to projects_url, notice: "Reel was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @reel.update(reel_params)
    respond_to { |format| format.js { render nothing: true } }
    redirect_back(fallback_location: root_path)
  end

  def destroy
    if @reel.destroy
      redirect_to reels_path(product_id: @reel.project_id), notice: "Project was successfully destroyed."
    end
  end

  def editor
    @templates = @reel.templates.all
  end

  def text_to_video
    fb_token = current_user.facebook_token
    fetch_data = FacebookService.new({token: fb_token})
    @data = fetch_data.facebook_call(fb_token)

    @reel = Reel.find_by(id: params[:reel_id])
    @templates = @reel.templates.last
    script = params[:script_text]
    shots = ShotstackService.new
    audio_src = rails_blob_url(@templates.file, disposition: :inline)
    id = shots.text_to_video(script, audio_src,  session[:video_data_url] , session[:image_data_url])
    api_client = Shotstack::EditApi.new
    sleep(30)
    @result = api_client.get_render(id, { data: false, merged: true }).response
    @reel.url = @result.url
    @reel.save
  end

  def fetch_url
    session[:image_data_url] = params[:image_data_Url]
    session[:video_data_url] = params[:video_data_Url]
  end

  private

  def set_reel
    @reel = Reel.find(params[:id])
  end

  def reel_param
    params.require(:reel).permit(:script)
  end

  def reel_params
    params.require(:reel).permit(:video_set, :keywords, :no_of_video, :platform, :cta, :project_id)
  end

  def load_data
    response = HTTParty.get("https://api.elevenlabs.io/v1/voices")
    @voices = response.parsed_response["voices"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end
end

app/controllers/videos_controller.rb
require "google/apis/youtube_v3"
require "net/http"

class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    youtube_service = YoutubeService.new
    if @video.save

      file_path = Rails.root.join("storage", "video", "test.mp4")
      File.open(file_path, "wb") do |file|
        file.write(@video.video_file.download)
      end
      youtube_service.upload_video_to_youtube(@video, current_user)
      redirect_to videos_path, notice: "Video was successfully uploaded."
    else
      render :new
    end
  end

  def update
    if @video.update(video_params)
      redirect_to root_path, notice: "Video was successfully updated."
    else
      render :edit
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :description, :video_file, :privacy_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categorize_data
    @data.group_by{ |item| item["type"] }.transform_values{ |items| items.map { |item| [item["name"], "#{item["id"]},#{item["type"]}"]}}
  end
end

app/helpers/chat_gpt_helper.rb
module ChatGptHelper
end

app/helpers/integration_helper.rb
module IntegrationHelper
  def fb_status
    @status == 'connected'
  end

end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/record_audio_helper.rb
module RecordAudioHelper
end

app/helpers/reels_helper.rb
module ReelsHelper
end

app/helpers/text_to_speech_helper.rb
module TextToSpeechHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top-left">
  <div class="container">
    <a class="navbar-brand " href="/"><img src="https://content.reelapps.io/static/media/LOGO.c4ba0a75af69c59a6576.png" width="50%"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse nav-light" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item active">
          <a class="nav-link site-menu js-clone-nav mr-auto d-none d-lg-block"><%=link_to "Dashboard" ,root_path,class: 'text-decoration-none  nav-link text-light site-menu' %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%=link_to "Projects" ,projects_path,class: 'text-decoration-none  nav-link text-light site-menu' %></a>
        </li>
        <!--        <li class="nav-item">-->
        <!--          <a class="nav-link text-color"><%#= link_to 'Text_to_Speech',  text_to_speech_index_path,class: 'd-block text-decoration-none  nav-link text-light site-menu'%></a>-->
        <!--        </li>-->
        <li class="nav-item text-color">
          <a class="nav-link text-color text-decoration-none  nav-link text-light site-menu"><%= link_to 'Integrations ',  integration_path,class: 'text-decoration-none  nav-link text-light site-menu' %></a>
        </li>
        <li class="nav-item dropdown menu-end">
          <a class="nav-link dropdown-toggle text_overflow text-light" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Welcome<br/>
            <% if current_user.present?%>
              <%=current_user.email %>
            <%end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-secondary" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="navbar-nav dropdown-item" href="#">My Account</a></li>
            <li><a class="navbar-nav dropdown-item" href="#">Privacy Setting</a></li>
            <li><a class="navbar-nav dropdown-item" href="#">Help & Support</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout',destroy_user_session_path,data: { turbo_method: :delete} ,class: 'navbar-nav dropdown-item' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contentreels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <%= yield :custom_js %>
    <%= javascript_include_tag 'application',type: 'module'%>

  </head>
  <body>
    <%if current_user.present? %>
      <%=render 'layouts/navbar'%>
    <%end %>
    <%= render partial: "shared/flash_messages" %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div id='flash'>
   <script>
     <% if flash[:success] || flash[:notice] %>
        toastr.success('<span><%= flash[:notice] %></span>')
     <% end %>
     <% if flash[:info] %>
        toastr.info('<span><%= flash[:info] %></span>')
     <% end %>
     <% if flash[:danger] || flash[:alert] %>
        toastr.error('<span><%= flash[:alert] %></span>')
     <% end %>
   </script>
  </div>
<% end %>

app/views/templates/_audio_index.html.erb
<br>
<div class="container">
  <%= form_tag(text_to_speech_path, method: :get) do %>
    <label style="cursor: auto">Select Voice:</label>
    <%= select_tag :voice, options_for_select(@voices.pluck("name", "voice_id"))  ,{prompt: 'Select Voice'} %>
    <br>
    <br>
    <label class="">Enter Text</label>
    <br>
    <%= hidden_field_tag :reel_id, params[:id] %>
    <%= text_area_tag :text%>
    <br>
    <%= submit_tag 'Submit', class: 'mk-button left-corners right-corners blue-button', id:"submit-btn"%>
  <% end %>
</div>
<br>
<br>
<br>

app/views/templates/_form.html.erb
<%= form_for template do |form| %>
  <% if template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this Reel from being saved:</h2>
      <ul>
        <% template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-body bg-dark">
    <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3>Create New Reel</h3>
            <p>Fill in the data below.</p>
            <div class="form-group">
              <%= form.label :file %>
              <%= form.file_field :file, class: "form-control", placeholder: "Upload Video" %>
            </div>
            <%= form.hidden_field :reel_id, value: @template.reel_id %>
            <br>
            <div>
              <%= form.submit "Create", class: "btn btn-sm modal_buttons text-light border" %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/templates/_image_show.html.erb
<div id="show_data">
  <%= form_with url: search_image_path, method: :post do |form| %>
    <label>Search Image</label>
    <%= form.text_field :image_text %>
    <br>
    <%= form.submit 'Submit' %>
  <% end %>
  <br>
  <br>
  <%if @image_url.present? %>
  <% @image_url.each do |i_url| %>
      <div class="image_hover center_align" style="height:106px;width:106px; float: right">
    <%= image_tag(i_url.src["original"], style: "height:100px;width:100px; cursor: pointer" ,class: "image_url")  %>
      </div>
  <% end %>
  <% end %>
  <%= form_with url: search_video_path, method: :post, remote: true do |form| %>
    <label>Search Video</label>
    <%= form.text_field :video_text %>
    <br>
    <%= form.submit 'Submit' %>
  <% end %>
  <br>
  <br>
  <% if @video_url.present? %>
    <% @video_url.each do |v_url| %>
      <div class="image_hover center_align" style="height:164px;width:345px;">
      <%= video_tag v_url, controls: true, width: 340, height: 160,class: "video_url", style:"cursor: pointer" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/templates/_record_microphone_audio.html.erb
<%= form_tag(microphone_path, method: :post, id: 'audio-form') do %>
  <%= button_tag 'Start Recording', id: 'js-start', type: 'button' %>
  <%= button_tag 'Stop Recording', id: 'js-stop', type: 'button' %>
  <%= hidden_field_tag :reel_id, params[:id] %>
  <%= hidden_field_tag 'audio_blob', nil, id: 'audio' %>
  <%= submit_tag 'Save Audio' %>
<% end %>

app/views/templates/_template.html.erb
<div class="col-md-6">
  <div class="card mb-3">
    <% if template.file.attached? && template.file.content_type.include?("video") %>
      <video controls class="card-img-top" width="60%">
        <source src="<%= url_for(template.file) %>" type="<%= template.file.content_type %>">
      </video>
    <% elsif template.file.attached? && template.file.content_type.include?("audio") %>
      <audio controls class="card-img-top" width="60%">
        <source src="<%= url_for(template.file) %>" type="<%= template.file.content_type %>">
      </audio>
    <% elsif template.file.attached? && template.file.content_type.include?("image") %>
      <%= image_tag url_for(template.file) %>
    <% else %>
      <div class="card-body">
        <p class="card-text">No video file attached and file is not supported.</p>
      </div>
    <% end %>

  </div>
</div>

app/views/templates/_text.html.erb
<div id="show_data" class="container">
  <%if @reel.script %>
  <%@reel.script.split('.').each_with_index do |text| %>
    <div class="card">
      <div class="card-body">
       <%= text %>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/templates/index.html.erb
<div class="container">
  <h1>All Video Files</h1>
  <div class="row">
    <%= render partial: "templates/template", collection: @templates %>
  </div>
</div>

app/views/templates/new.html.erb
<%= render "templates/form", template: @template %>

app/views/templates/show_microphone.html.erb
<audio controls id="recordedAudio">
  <source src="<%= j(params[:audio_blob]) %>" type="audio/mpeg">
</audio>